package com.member.entities.po;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
public class Member {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.id
     *
     * @mbg.generated Sat Mar 05 19:43:37 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.loginacct
     *
     * @mbg.generated Sat Mar 05 19:43:37 CST 2022
     */
    private String loginacct;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.userpswd
     *
     * @mbg.generated Sat Mar 05 19:43:37 CST 2022
     */
    private String userpswd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.username
     *
     * @mbg.generated Sat Mar 05 19:43:37 CST 2022
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.email
     *
     * @mbg.generated Sat Mar 05 19:43:37 CST 2022
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.authstatus
     *
     * @mbg.generated Sat Mar 05 19:43:37 CST 2022
     */
    private Integer authstatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.usertype
     *
     * @mbg.generated Sat Mar 05 19:43:37 CST 2022
     */
    private Integer usertype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.realname
     *
     * @mbg.generated Sat Mar 05 19:43:37 CST 2022
     */
    private String realname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.cardnum
     *
     * @mbg.generated Sat Mar 05 19:43:37 CST 2022
     */
    private String cardnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.accttype
     *
     * @mbg.generated Sat Mar 05 19:43:37 CST 2022
     */
    private Integer accttype;
}