package com.member.entities.po;

public class ProjectItemPicturePO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_item_picture.id
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_item_picture.project_id
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    private Integer projectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_item_picture.item_picture_path
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    private String itemPicturePath;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_item_picture.id
     *
     * @return the value of project_item_picture.id
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_item_picture.id
     *
     * @param id the value for project_item_picture.id
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_item_picture.project_id
     *
     * @return the value of project_item_picture.project_id
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_item_picture.project_id
     *
     * @param projectId the value for project_item_picture.project_id
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_item_picture.item_picture_path
     *
     * @return the value of project_item_picture.item_picture_path
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    public String getItemPicturePath() {
        return itemPicturePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_item_picture.item_picture_path
     *
     * @param itemPicturePath the value for project_item_picture.item_picture_path
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    public void setItemPicturePath(String itemPicturePath) {
        this.itemPicturePath = itemPicturePath;
    }
}