package com.member.entities.po;

public class ProjectPO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.id
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.project_name
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    private String projectName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.project_description
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    private String projectDescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.money
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    private Long money;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.day
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    private Integer day;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.status
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.launch_time
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    private String launchTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.money_raised
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    private Long moneyRaised;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.supporter
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    private Integer supporter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.completion_percent
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    private Integer completionPercent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.member_id
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    private Integer memberId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.create_time
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    private String createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.follower
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    private Integer follower;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.header_picture_path
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    private String headerPicturePath;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.id
     *
     * @return the value of project.id
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.id
     *
     * @param id the value for project.id
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.project_name
     *
     * @return the value of project.project_name
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    public String getProjectName() {
        return projectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.project_name
     *
     * @param projectName the value for project.project_name
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    public void setProjectName(String projectName) {
        this.projectName = projectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.project_description
     *
     * @return the value of project.project_description
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    public String getProjectDescription() {
        return projectDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.project_description
     *
     * @param projectDescription the value for project.project_description
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    public void setProjectDescription(String projectDescription) {
        this.projectDescription = projectDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.money
     *
     * @return the value of project.money
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    public Long getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.money
     *
     * @param money the value for project.money
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    public void setMoney(Long money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.day
     *
     * @return the value of project.day
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    public Integer getDay() {
        return day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.day
     *
     * @param day the value for project.day
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    public void setDay(Integer day) {
        this.day = day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.status
     *
     * @return the value of project.status
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.status
     *
     * @param status the value for project.status
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.launch_time
     *
     * @return the value of project.launch_time
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    public String getLaunchTime() {
        return launchTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.launch_time
     *
     * @param launchTime the value for project.launch_time
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    public void setLaunchTime(String launchTime) {
        this.launchTime = launchTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.money_raised
     *
     * @return the value of project.money_raised
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    public Long getMoneyRaised() {
        return moneyRaised;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.money_raised
     *
     * @param moneyRaised the value for project.money_raised
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    public void setMoneyRaised(Long moneyRaised) {
        this.moneyRaised = moneyRaised;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.supporter
     *
     * @return the value of project.supporter
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    public Integer getSupporter() {
        return supporter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.supporter
     *
     * @param supporter the value for project.supporter
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    public void setSupporter(Integer supporter) {
        this.supporter = supporter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.completion_percent
     *
     * @return the value of project.completion_percent
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    public Integer getCompletionPercent() {
        return completionPercent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.completion_percent
     *
     * @param completionPercent the value for project.completion_percent
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    public void setCompletionPercent(Integer completionPercent) {
        this.completionPercent = completionPercent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.member_id
     *
     * @return the value of project.member_id
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    public Integer getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.member_id
     *
     * @param memberId the value for project.member_id
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    public void setMemberId(Integer memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.create_time
     *
     * @return the value of project.create_time
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.create_time
     *
     * @param createTime the value for project.create_time
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.follower
     *
     * @return the value of project.follower
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    public Integer getFollower() {
        return follower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.follower
     *
     * @param follower the value for project.follower
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    public void setFollower(Integer follower) {
        this.follower = follower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.header_picture_path
     *
     * @return the value of project.header_picture_path
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    public String getHeaderPicturePath() {
        return headerPicturePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.header_picture_path
     *
     * @param headerPicturePath the value for project.header_picture_path
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    public void setHeaderPicturePath(String headerPicturePath) {
        this.headerPicturePath = headerPicturePath;
    }
}