package com.member.entities.po;

import java.util.ArrayList;
import java.util.List;

public class RewardPOExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table reward
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table reward
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table reward
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    public RewardPOExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table reward
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andProjectIdIsNull() {
            addCriterion("project_id is null");
            return (Criteria) this;
        }

        public Criteria andProjectIdIsNotNull() {
            addCriterion("project_id is not null");
            return (Criteria) this;
        }

        public Criteria andProjectIdEqualTo(Integer value) {
            addCriterion("project_id =", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotEqualTo(Integer value) {
            addCriterion("project_id <>", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdGreaterThan(Integer value) {
            addCriterion("project_id >", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("project_id >=", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdLessThan(Integer value) {
            addCriterion("project_id <", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdLessThanOrEqualTo(Integer value) {
            addCriterion("project_id <=", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdIn(List<Integer> values) {
            addCriterion("project_id in", values, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotIn(List<Integer> values) {
            addCriterion("project_id not in", values, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdBetween(Integer value1, Integer value2) {
            addCriterion("project_id between", value1, value2, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotBetween(Integer value1, Integer value2) {
            addCriterion("project_id not between", value1, value2, "projectId");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(Integer value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(Integer value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(Integer value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(Integer value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(Integer value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<Integer> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<Integer> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(Integer value1, Integer value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andSupportMoneyIsNull() {
            addCriterion("support_money is null");
            return (Criteria) this;
        }

        public Criteria andSupportMoneyIsNotNull() {
            addCriterion("support_money is not null");
            return (Criteria) this;
        }

        public Criteria andSupportMoneyEqualTo(Integer value) {
            addCriterion("support_money =", value, "supportMoney");
            return (Criteria) this;
        }

        public Criteria andSupportMoneyNotEqualTo(Integer value) {
            addCriterion("support_money <>", value, "supportMoney");
            return (Criteria) this;
        }

        public Criteria andSupportMoneyGreaterThan(Integer value) {
            addCriterion("support_money >", value, "supportMoney");
            return (Criteria) this;
        }

        public Criteria andSupportMoneyGreaterThanOrEqualTo(Integer value) {
            addCriterion("support_money >=", value, "supportMoney");
            return (Criteria) this;
        }

        public Criteria andSupportMoneyLessThan(Integer value) {
            addCriterion("support_money <", value, "supportMoney");
            return (Criteria) this;
        }

        public Criteria andSupportMoneyLessThanOrEqualTo(Integer value) {
            addCriterion("support_money <=", value, "supportMoney");
            return (Criteria) this;
        }

        public Criteria andSupportMoneyIn(List<Integer> values) {
            addCriterion("support_money in", values, "supportMoney");
            return (Criteria) this;
        }

        public Criteria andSupportMoneyNotIn(List<Integer> values) {
            addCriterion("support_money not in", values, "supportMoney");
            return (Criteria) this;
        }

        public Criteria andSupportMoneyBetween(Integer value1, Integer value2) {
            addCriterion("support_money between", value1, value2, "supportMoney");
            return (Criteria) this;
        }

        public Criteria andSupportMoneyNotBetween(Integer value1, Integer value2) {
            addCriterion("support_money not between", value1, value2, "supportMoney");
            return (Criteria) this;
        }

        public Criteria andContentIsNull() {
            addCriterion("content is null");
            return (Criteria) this;
        }

        public Criteria andContentIsNotNull() {
            addCriterion("content is not null");
            return (Criteria) this;
        }

        public Criteria andContentEqualTo(String value) {
            addCriterion("content =", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotEqualTo(String value) {
            addCriterion("content <>", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentGreaterThan(String value) {
            addCriterion("content >", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentGreaterThanOrEqualTo(String value) {
            addCriterion("content >=", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLessThan(String value) {
            addCriterion("content <", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLessThanOrEqualTo(String value) {
            addCriterion("content <=", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLike(String value) {
            addCriterion("content like", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotLike(String value) {
            addCriterion("content not like", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentIn(List<String> values) {
            addCriterion("content in", values, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotIn(List<String> values) {
            addCriterion("content not in", values, "content");
            return (Criteria) this;
        }

        public Criteria andContentBetween(String value1, String value2) {
            addCriterion("content between", value1, value2, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotBetween(String value1, String value2) {
            addCriterion("content not between", value1, value2, "content");
            return (Criteria) this;
        }

        public Criteria andCountIsNull() {
            addCriterion("count is null");
            return (Criteria) this;
        }

        public Criteria andCountIsNotNull() {
            addCriterion("count is not null");
            return (Criteria) this;
        }

        public Criteria andCountEqualTo(Integer value) {
            addCriterion("count =", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountNotEqualTo(Integer value) {
            addCriterion("count <>", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountGreaterThan(Integer value) {
            addCriterion("count >", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("count >=", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountLessThan(Integer value) {
            addCriterion("count <", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountLessThanOrEqualTo(Integer value) {
            addCriterion("count <=", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountIn(List<Integer> values) {
            addCriterion("count in", values, "count");
            return (Criteria) this;
        }

        public Criteria andCountNotIn(List<Integer> values) {
            addCriterion("count not in", values, "count");
            return (Criteria) this;
        }

        public Criteria andCountBetween(Integer value1, Integer value2) {
            addCriterion("count between", value1, value2, "count");
            return (Criteria) this;
        }

        public Criteria andCountNotBetween(Integer value1, Integer value2) {
            addCriterion("count not between", value1, value2, "count");
            return (Criteria) this;
        }

        public Criteria andIsPurchaseLimitsIsNull() {
            addCriterion("is_purchase_limits is null");
            return (Criteria) this;
        }

        public Criteria andIsPurchaseLimitsIsNotNull() {
            addCriterion("is_purchase_limits is not null");
            return (Criteria) this;
        }

        public Criteria andIsPurchaseLimitsEqualTo(Integer value) {
            addCriterion("is_purchase_limits =", value, "isPurchaseLimits");
            return (Criteria) this;
        }

        public Criteria andIsPurchaseLimitsNotEqualTo(Integer value) {
            addCriterion("is_purchase_limits <>", value, "isPurchaseLimits");
            return (Criteria) this;
        }

        public Criteria andIsPurchaseLimitsGreaterThan(Integer value) {
            addCriterion("is_purchase_limits >", value, "isPurchaseLimits");
            return (Criteria) this;
        }

        public Criteria andIsPurchaseLimitsGreaterThanOrEqualTo(Integer value) {
            addCriterion("is_purchase_limits >=", value, "isPurchaseLimits");
            return (Criteria) this;
        }

        public Criteria andIsPurchaseLimitsLessThan(Integer value) {
            addCriterion("is_purchase_limits <", value, "isPurchaseLimits");
            return (Criteria) this;
        }

        public Criteria andIsPurchaseLimitsLessThanOrEqualTo(Integer value) {
            addCriterion("is_purchase_limits <=", value, "isPurchaseLimits");
            return (Criteria) this;
        }

        public Criteria andIsPurchaseLimitsIn(List<Integer> values) {
            addCriterion("is_purchase_limits in", values, "isPurchaseLimits");
            return (Criteria) this;
        }

        public Criteria andIsPurchaseLimitsNotIn(List<Integer> values) {
            addCriterion("is_purchase_limits not in", values, "isPurchaseLimits");
            return (Criteria) this;
        }

        public Criteria andIsPurchaseLimitsBetween(Integer value1, Integer value2) {
            addCriterion("is_purchase_limits between", value1, value2, "isPurchaseLimits");
            return (Criteria) this;
        }

        public Criteria andIsPurchaseLimitsNotBetween(Integer value1, Integer value2) {
            addCriterion("is_purchase_limits not between", value1, value2, "isPurchaseLimits");
            return (Criteria) this;
        }

        public Criteria andPurchaseCountIsNull() {
            addCriterion("purchase_count is null");
            return (Criteria) this;
        }

        public Criteria andPurchaseCountIsNotNull() {
            addCriterion("purchase_count is not null");
            return (Criteria) this;
        }

        public Criteria andPurchaseCountEqualTo(Integer value) {
            addCriterion("purchase_count =", value, "purchaseCount");
            return (Criteria) this;
        }

        public Criteria andPurchaseCountNotEqualTo(Integer value) {
            addCriterion("purchase_count <>", value, "purchaseCount");
            return (Criteria) this;
        }

        public Criteria andPurchaseCountGreaterThan(Integer value) {
            addCriterion("purchase_count >", value, "purchaseCount");
            return (Criteria) this;
        }

        public Criteria andPurchaseCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("purchase_count >=", value, "purchaseCount");
            return (Criteria) this;
        }

        public Criteria andPurchaseCountLessThan(Integer value) {
            addCriterion("purchase_count <", value, "purchaseCount");
            return (Criteria) this;
        }

        public Criteria andPurchaseCountLessThanOrEqualTo(Integer value) {
            addCriterion("purchase_count <=", value, "purchaseCount");
            return (Criteria) this;
        }

        public Criteria andPurchaseCountIn(List<Integer> values) {
            addCriterion("purchase_count in", values, "purchaseCount");
            return (Criteria) this;
        }

        public Criteria andPurchaseCountNotIn(List<Integer> values) {
            addCriterion("purchase_count not in", values, "purchaseCount");
            return (Criteria) this;
        }

        public Criteria andPurchaseCountBetween(Integer value1, Integer value2) {
            addCriterion("purchase_count between", value1, value2, "purchaseCount");
            return (Criteria) this;
        }

        public Criteria andPurchaseCountNotBetween(Integer value1, Integer value2) {
            addCriterion("purchase_count not between", value1, value2, "purchaseCount");
            return (Criteria) this;
        }

        public Criteria andFreightIsNull() {
            addCriterion("freight is null");
            return (Criteria) this;
        }

        public Criteria andFreightIsNotNull() {
            addCriterion("freight is not null");
            return (Criteria) this;
        }

        public Criteria andFreightEqualTo(Integer value) {
            addCriterion("freight =", value, "freight");
            return (Criteria) this;
        }

        public Criteria andFreightNotEqualTo(Integer value) {
            addCriterion("freight <>", value, "freight");
            return (Criteria) this;
        }

        public Criteria andFreightGreaterThan(Integer value) {
            addCriterion("freight >", value, "freight");
            return (Criteria) this;
        }

        public Criteria andFreightGreaterThanOrEqualTo(Integer value) {
            addCriterion("freight >=", value, "freight");
            return (Criteria) this;
        }

        public Criteria andFreightLessThan(Integer value) {
            addCriterion("freight <", value, "freight");
            return (Criteria) this;
        }

        public Criteria andFreightLessThanOrEqualTo(Integer value) {
            addCriterion("freight <=", value, "freight");
            return (Criteria) this;
        }

        public Criteria andFreightIn(List<Integer> values) {
            addCriterion("freight in", values, "freight");
            return (Criteria) this;
        }

        public Criteria andFreightNotIn(List<Integer> values) {
            addCriterion("freight not in", values, "freight");
            return (Criteria) this;
        }

        public Criteria andFreightBetween(Integer value1, Integer value2) {
            addCriterion("freight between", value1, value2, "freight");
            return (Criteria) this;
        }

        public Criteria andFreightNotBetween(Integer value1, Integer value2) {
            addCriterion("freight not between", value1, value2, "freight");
            return (Criteria) this;
        }

        public Criteria andIsReceiptIsNull() {
            addCriterion("is_receipt is null");
            return (Criteria) this;
        }

        public Criteria andIsReceiptIsNotNull() {
            addCriterion("is_receipt is not null");
            return (Criteria) this;
        }

        public Criteria andIsReceiptEqualTo(Integer value) {
            addCriterion("is_receipt =", value, "isReceipt");
            return (Criteria) this;
        }

        public Criteria andIsReceiptNotEqualTo(Integer value) {
            addCriterion("is_receipt <>", value, "isReceipt");
            return (Criteria) this;
        }

        public Criteria andIsReceiptGreaterThan(Integer value) {
            addCriterion("is_receipt >", value, "isReceipt");
            return (Criteria) this;
        }

        public Criteria andIsReceiptGreaterThanOrEqualTo(Integer value) {
            addCriterion("is_receipt >=", value, "isReceipt");
            return (Criteria) this;
        }

        public Criteria andIsReceiptLessThan(Integer value) {
            addCriterion("is_receipt <", value, "isReceipt");
            return (Criteria) this;
        }

        public Criteria andIsReceiptLessThanOrEqualTo(Integer value) {
            addCriterion("is_receipt <=", value, "isReceipt");
            return (Criteria) this;
        }

        public Criteria andIsReceiptIn(List<Integer> values) {
            addCriterion("is_receipt in", values, "isReceipt");
            return (Criteria) this;
        }

        public Criteria andIsReceiptNotIn(List<Integer> values) {
            addCriterion("is_receipt not in", values, "isReceipt");
            return (Criteria) this;
        }

        public Criteria andIsReceiptBetween(Integer value1, Integer value2) {
            addCriterion("is_receipt between", value1, value2, "isReceipt");
            return (Criteria) this;
        }

        public Criteria andIsReceiptNotBetween(Integer value1, Integer value2) {
            addCriterion("is_receipt not between", value1, value2, "isReceipt");
            return (Criteria) this;
        }

        public Criteria andDayToRewardIsNull() {
            addCriterion("day_to_reward is null");
            return (Criteria) this;
        }

        public Criteria andDayToRewardIsNotNull() {
            addCriterion("day_to_reward is not null");
            return (Criteria) this;
        }

        public Criteria andDayToRewardEqualTo(Integer value) {
            addCriterion("day_to_reward =", value, "dayToReward");
            return (Criteria) this;
        }

        public Criteria andDayToRewardNotEqualTo(Integer value) {
            addCriterion("day_to_reward <>", value, "dayToReward");
            return (Criteria) this;
        }

        public Criteria andDayToRewardGreaterThan(Integer value) {
            addCriterion("day_to_reward >", value, "dayToReward");
            return (Criteria) this;
        }

        public Criteria andDayToRewardGreaterThanOrEqualTo(Integer value) {
            addCriterion("day_to_reward >=", value, "dayToReward");
            return (Criteria) this;
        }

        public Criteria andDayToRewardLessThan(Integer value) {
            addCriterion("day_to_reward <", value, "dayToReward");
            return (Criteria) this;
        }

        public Criteria andDayToRewardLessThanOrEqualTo(Integer value) {
            addCriterion("day_to_reward <=", value, "dayToReward");
            return (Criteria) this;
        }

        public Criteria andDayToRewardIn(List<Integer> values) {
            addCriterion("day_to_reward in", values, "dayToReward");
            return (Criteria) this;
        }

        public Criteria andDayToRewardNotIn(List<Integer> values) {
            addCriterion("day_to_reward not in", values, "dayToReward");
            return (Criteria) this;
        }

        public Criteria andDayToRewardBetween(Integer value1, Integer value2) {
            addCriterion("day_to_reward between", value1, value2, "dayToReward");
            return (Criteria) this;
        }

        public Criteria andDayToRewardNotBetween(Integer value1, Integer value2) {
            addCriterion("day_to_reward not between", value1, value2, "dayToReward");
            return (Criteria) this;
        }

        public Criteria andDescribePicturePathIsNull() {
            addCriterion("describe_picture_path is null");
            return (Criteria) this;
        }

        public Criteria andDescribePicturePathIsNotNull() {
            addCriterion("describe_picture_path is not null");
            return (Criteria) this;
        }

        public Criteria andDescribePicturePathEqualTo(String value) {
            addCriterion("describe_picture_path =", value, "describePicturePath");
            return (Criteria) this;
        }

        public Criteria andDescribePicturePathNotEqualTo(String value) {
            addCriterion("describe_picture_path <>", value, "describePicturePath");
            return (Criteria) this;
        }

        public Criteria andDescribePicturePathGreaterThan(String value) {
            addCriterion("describe_picture_path >", value, "describePicturePath");
            return (Criteria) this;
        }

        public Criteria andDescribePicturePathGreaterThanOrEqualTo(String value) {
            addCriterion("describe_picture_path >=", value, "describePicturePath");
            return (Criteria) this;
        }

        public Criteria andDescribePicturePathLessThan(String value) {
            addCriterion("describe_picture_path <", value, "describePicturePath");
            return (Criteria) this;
        }

        public Criteria andDescribePicturePathLessThanOrEqualTo(String value) {
            addCriterion("describe_picture_path <=", value, "describePicturePath");
            return (Criteria) this;
        }

        public Criteria andDescribePicturePathLike(String value) {
            addCriterion("describe_picture_path like", value, "describePicturePath");
            return (Criteria) this;
        }

        public Criteria andDescribePicturePathNotLike(String value) {
            addCriterion("describe_picture_path not like", value, "describePicturePath");
            return (Criteria) this;
        }

        public Criteria andDescribePicturePathIn(List<String> values) {
            addCriterion("describe_picture_path in", values, "describePicturePath");
            return (Criteria) this;
        }

        public Criteria andDescribePicturePathNotIn(List<String> values) {
            addCriterion("describe_picture_path not in", values, "describePicturePath");
            return (Criteria) this;
        }

        public Criteria andDescribePicturePathBetween(String value1, String value2) {
            addCriterion("describe_picture_path between", value1, value2, "describePicturePath");
            return (Criteria) this;
        }

        public Criteria andDescribePicturePathNotBetween(String value1, String value2) {
            addCriterion("describe_picture_path not between", value1, value2, "describePicturePath");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table reward
     *
     * @mbg.generated do_not_delete_during_merge Wed Apr 13 21:45:49 CST 2022
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table reward
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}