package com.member.entities.po;

public class RewardPO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward.id
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward.project_id
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    private Integer projectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward.type
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward.support_money
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    private Integer supportMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward.content
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward.count
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    private Integer count;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward.is_purchase_limits
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    private Integer isPurchaseLimits;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward.purchase_count
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    private Integer purchaseCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward.freight
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    private Integer freight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward.is_receipt
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    private Integer isReceipt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward.day_to_reward
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    private Integer dayToReward;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward.describe_picture_path
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    private String describePicturePath;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward.id
     *
     * @return the value of reward.id
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward.id
     *
     * @param id the value for reward.id
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward.project_id
     *
     * @return the value of reward.project_id
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward.project_id
     *
     * @param projectId the value for reward.project_id
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward.type
     *
     * @return the value of reward.type
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward.type
     *
     * @param type the value for reward.type
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward.support_money
     *
     * @return the value of reward.support_money
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    public Integer getSupportMoney() {
        return supportMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward.support_money
     *
     * @param supportMoney the value for reward.support_money
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    public void setSupportMoney(Integer supportMoney) {
        this.supportMoney = supportMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward.content
     *
     * @return the value of reward.content
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward.content
     *
     * @param content the value for reward.content
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward.count
     *
     * @return the value of reward.count
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward.count
     *
     * @param count the value for reward.count
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward.is_purchase_limits
     *
     * @return the value of reward.is_purchase_limits
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    public Integer getIsPurchaseLimits() {
        return isPurchaseLimits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward.is_purchase_limits
     *
     * @param isPurchaseLimits the value for reward.is_purchase_limits
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    public void setIsPurchaseLimits(Integer isPurchaseLimits) {
        this.isPurchaseLimits = isPurchaseLimits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward.purchase_count
     *
     * @return the value of reward.purchase_count
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    public Integer getPurchaseCount() {
        return purchaseCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward.purchase_count
     *
     * @param purchaseCount the value for reward.purchase_count
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    public void setPurchaseCount(Integer purchaseCount) {
        this.purchaseCount = purchaseCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward.freight
     *
     * @return the value of reward.freight
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    public Integer getFreight() {
        return freight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward.freight
     *
     * @param freight the value for reward.freight
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    public void setFreight(Integer freight) {
        this.freight = freight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward.is_receipt
     *
     * @return the value of reward.is_receipt
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    public Integer getIsReceipt() {
        return isReceipt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward.is_receipt
     *
     * @param isReceipt the value for reward.is_receipt
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    public void setIsReceipt(Integer isReceipt) {
        this.isReceipt = isReceipt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward.day_to_reward
     *
     * @return the value of reward.day_to_reward
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    public Integer getDayToReward() {
        return dayToReward;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward.day_to_reward
     *
     * @param dayToReward the value for reward.day_to_reward
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    public void setDayToReward(Integer dayToReward) {
        this.dayToReward = dayToReward;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward.describe_picture_path
     *
     * @return the value of reward.describe_picture_path
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    public String getDescribePicturePath() {
        return describePicturePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward.describe_picture_path
     *
     * @param describePicturePath the value for reward.describe_picture_path
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    public void setDescribePicturePath(String describePicturePath) {
        this.describePicturePath = describePicturePath;
    }
}