package com.member.entities.po;

public class SponsorInfoPO {

    private Integer id;

    private Integer memberId;

    private String descriptionSimple;

    private String descriptionDetail;

    private String phone;

    private String customerServiceServicePhone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_sponsor_info.id
     *
     * @return the value of project_sponsor_info.id
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_sponsor_info.id
     *
     * @param id the value for project_sponsor_info.id
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_sponsor_info.member_id
     *
     * @return the value of project_sponsor_info.member_id
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    public Integer getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_sponsor_info.member_id
     *
     * @param memberId the value for project_sponsor_info.member_id
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    public void setMemberId(Integer memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_sponsor_info.description_simple
     *
     * @return the value of project_sponsor_info.description_simple
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    public String getDescriptionSimple() {
        return descriptionSimple;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_sponsor_info.description_simple
     *
     * @param descriptionSimple the value for project_sponsor_info.description_simple
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    public void setDescriptionSimple(String descriptionSimple) {
        this.descriptionSimple = descriptionSimple;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_sponsor_info.description_detail
     *
     * @return the value of project_sponsor_info.description_detail
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    public String getDescriptionDetail() {
        return descriptionDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_sponsor_info.description_detail
     *
     * @param descriptionDetail the value for project_sponsor_info.description_detail
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    public void setDescriptionDetail(String descriptionDetail) {
        this.descriptionDetail = descriptionDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_sponsor_info.phone
     *
     * @return the value of project_sponsor_info.phone
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_sponsor_info.phone
     *
     * @param phone the value for project_sponsor_info.phone
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_sponsor_info.customer_service_service_phone
     *
     * @return the value of project_sponsor_info.customer_service_service_phone
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    public String getCustomerServiceServicePhone() {
        return customerServiceServicePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_sponsor_info.customer_service_service_phone
     *
     * @param customerServiceServicePhone the value for project_sponsor_info.customer_service_service_phone
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    public void setCustomerServiceServicePhone(String customerServiceServicePhone) {
        this.customerServiceServicePhone = customerServiceServicePhone;
    }
}