package com.member.entities.po;

public class SponsorConfirmInfoPO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sponsor_confirm_info.id
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sponsor_confirm_info.member_id
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    private Integer memberId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sponsor_confirm_info.pay_account
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    private String payAccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sponsor_confirm_info.legal_id_number
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    private String legalIdNumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sponsor_confirm_info.id
     *
     * @return the value of sponsor_confirm_info.id
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sponsor_confirm_info.id
     *
     * @param id the value for sponsor_confirm_info.id
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sponsor_confirm_info.member_id
     *
     * @return the value of sponsor_confirm_info.member_id
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    public Integer getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sponsor_confirm_info.member_id
     *
     * @param memberId the value for sponsor_confirm_info.member_id
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    public void setMemberId(Integer memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sponsor_confirm_info.pay_account
     *
     * @return the value of sponsor_confirm_info.pay_account
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    public String getPayAccount() {
        return payAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sponsor_confirm_info.pay_account
     *
     * @param payAccount the value for sponsor_confirm_info.pay_account
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    public void setPayAccount(String payAccount) {
        this.payAccount = payAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sponsor_confirm_info.legal_id_number
     *
     * @return the value of sponsor_confirm_info.legal_id_number
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    public String getLegalIdNumber() {
        return legalIdNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sponsor_confirm_info.legal_id_number
     *
     * @param legalIdNumber the value for sponsor_confirm_info.legal_id_number
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    public void setLegalIdNumber(String legalIdNumber) {
        this.legalIdNumber = legalIdNumber;
    }
}