package com.member.entities.po;

import java.util.ArrayList;
import java.util.List;

public class SponsorInfoPOExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table project_sponsor_info
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table project_sponsor_info
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table project_sponsor_info
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_sponsor_info
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    public SponsorInfoPOExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_sponsor_info
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_sponsor_info
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_sponsor_info
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_sponsor_info
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_sponsor_info
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_sponsor_info
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_sponsor_info
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_sponsor_info
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_sponsor_info
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_sponsor_info
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table project_sponsor_info
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andMemberIdIsNull() {
            addCriterion("member_id is null");
            return (Criteria) this;
        }

        public Criteria andMemberIdIsNotNull() {
            addCriterion("member_id is not null");
            return (Criteria) this;
        }

        public Criteria andMemberIdEqualTo(Integer value) {
            addCriterion("member_id =", value, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdNotEqualTo(Integer value) {
            addCriterion("member_id <>", value, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdGreaterThan(Integer value) {
            addCriterion("member_id >", value, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("member_id >=", value, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdLessThan(Integer value) {
            addCriterion("member_id <", value, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdLessThanOrEqualTo(Integer value) {
            addCriterion("member_id <=", value, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdIn(List<Integer> values) {
            addCriterion("member_id in", values, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdNotIn(List<Integer> values) {
            addCriterion("member_id not in", values, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdBetween(Integer value1, Integer value2) {
            addCriterion("member_id between", value1, value2, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdNotBetween(Integer value1, Integer value2) {
            addCriterion("member_id not between", value1, value2, "memberId");
            return (Criteria) this;
        }

        public Criteria andDescriptionSimpleIsNull() {
            addCriterion("description_simple is null");
            return (Criteria) this;
        }

        public Criteria andDescriptionSimpleIsNotNull() {
            addCriterion("description_simple is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptionSimpleEqualTo(String value) {
            addCriterion("description_simple =", value, "descriptionSimple");
            return (Criteria) this;
        }

        public Criteria andDescriptionSimpleNotEqualTo(String value) {
            addCriterion("description_simple <>", value, "descriptionSimple");
            return (Criteria) this;
        }

        public Criteria andDescriptionSimpleGreaterThan(String value) {
            addCriterion("description_simple >", value, "descriptionSimple");
            return (Criteria) this;
        }

        public Criteria andDescriptionSimpleGreaterThanOrEqualTo(String value) {
            addCriterion("description_simple >=", value, "descriptionSimple");
            return (Criteria) this;
        }

        public Criteria andDescriptionSimpleLessThan(String value) {
            addCriterion("description_simple <", value, "descriptionSimple");
            return (Criteria) this;
        }

        public Criteria andDescriptionSimpleLessThanOrEqualTo(String value) {
            addCriterion("description_simple <=", value, "descriptionSimple");
            return (Criteria) this;
        }

        public Criteria andDescriptionSimpleLike(String value) {
            addCriterion("description_simple like", value, "descriptionSimple");
            return (Criteria) this;
        }

        public Criteria andDescriptionSimpleNotLike(String value) {
            addCriterion("description_simple not like", value, "descriptionSimple");
            return (Criteria) this;
        }

        public Criteria andDescriptionSimpleIn(List<String> values) {
            addCriterion("description_simple in", values, "descriptionSimple");
            return (Criteria) this;
        }

        public Criteria andDescriptionSimpleNotIn(List<String> values) {
            addCriterion("description_simple not in", values, "descriptionSimple");
            return (Criteria) this;
        }

        public Criteria andDescriptionSimpleBetween(String value1, String value2) {
            addCriterion("description_simple between", value1, value2, "descriptionSimple");
            return (Criteria) this;
        }

        public Criteria andDescriptionSimpleNotBetween(String value1, String value2) {
            addCriterion("description_simple not between", value1, value2, "descriptionSimple");
            return (Criteria) this;
        }

        public Criteria andDescriptionDetailIsNull() {
            addCriterion("description_detail is null");
            return (Criteria) this;
        }

        public Criteria andDescriptionDetailIsNotNull() {
            addCriterion("description_detail is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptionDetailEqualTo(String value) {
            addCriterion("description_detail =", value, "descriptionDetail");
            return (Criteria) this;
        }

        public Criteria andDescriptionDetailNotEqualTo(String value) {
            addCriterion("description_detail <>", value, "descriptionDetail");
            return (Criteria) this;
        }

        public Criteria andDescriptionDetailGreaterThan(String value) {
            addCriterion("description_detail >", value, "descriptionDetail");
            return (Criteria) this;
        }

        public Criteria andDescriptionDetailGreaterThanOrEqualTo(String value) {
            addCriterion("description_detail >=", value, "descriptionDetail");
            return (Criteria) this;
        }

        public Criteria andDescriptionDetailLessThan(String value) {
            addCriterion("description_detail <", value, "descriptionDetail");
            return (Criteria) this;
        }

        public Criteria andDescriptionDetailLessThanOrEqualTo(String value) {
            addCriterion("description_detail <=", value, "descriptionDetail");
            return (Criteria) this;
        }

        public Criteria andDescriptionDetailLike(String value) {
            addCriterion("description_detail like", value, "descriptionDetail");
            return (Criteria) this;
        }

        public Criteria andDescriptionDetailNotLike(String value) {
            addCriterion("description_detail not like", value, "descriptionDetail");
            return (Criteria) this;
        }

        public Criteria andDescriptionDetailIn(List<String> values) {
            addCriterion("description_detail in", values, "descriptionDetail");
            return (Criteria) this;
        }

        public Criteria andDescriptionDetailNotIn(List<String> values) {
            addCriterion("description_detail not in", values, "descriptionDetail");
            return (Criteria) this;
        }

        public Criteria andDescriptionDetailBetween(String value1, String value2) {
            addCriterion("description_detail between", value1, value2, "descriptionDetail");
            return (Criteria) this;
        }

        public Criteria andDescriptionDetailNotBetween(String value1, String value2) {
            addCriterion("description_detail not between", value1, value2, "descriptionDetail");
            return (Criteria) this;
        }

        public Criteria andPhoneIsNull() {
            addCriterion("phone is null");
            return (Criteria) this;
        }

        public Criteria andPhoneIsNotNull() {
            addCriterion("phone is not null");
            return (Criteria) this;
        }

        public Criteria andPhoneEqualTo(String value) {
            addCriterion("phone =", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotEqualTo(String value) {
            addCriterion("phone <>", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneGreaterThan(String value) {
            addCriterion("phone >", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("phone >=", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLessThan(String value) {
            addCriterion("phone <", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLessThanOrEqualTo(String value) {
            addCriterion("phone <=", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLike(String value) {
            addCriterion("phone like", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotLike(String value) {
            addCriterion("phone not like", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneIn(List<String> values) {
            addCriterion("phone in", values, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotIn(List<String> values) {
            addCriterion("phone not in", values, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneBetween(String value1, String value2) {
            addCriterion("phone between", value1, value2, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotBetween(String value1, String value2) {
            addCriterion("phone not between", value1, value2, "phone");
            return (Criteria) this;
        }

        public Criteria andCustomerServiceServicePhoneIsNull() {
            addCriterion("customer_service_service_phone is null");
            return (Criteria) this;
        }

        public Criteria andCustomerServiceServicePhoneIsNotNull() {
            addCriterion("customer_service_service_phone is not null");
            return (Criteria) this;
        }

        public Criteria andCustomerServiceServicePhoneEqualTo(String value) {
            addCriterion("customer_service_service_phone =", value, "customerServiceServicePhone");
            return (Criteria) this;
        }

        public Criteria andCustomerServiceServicePhoneNotEqualTo(String value) {
            addCriterion("customer_service_service_phone <>", value, "customerServiceServicePhone");
            return (Criteria) this;
        }

        public Criteria andCustomerServiceServicePhoneGreaterThan(String value) {
            addCriterion("customer_service_service_phone >", value, "customerServiceServicePhone");
            return (Criteria) this;
        }

        public Criteria andCustomerServiceServicePhoneGreaterThanOrEqualTo(String value) {
            addCriterion("customer_service_service_phone >=", value, "customerServiceServicePhone");
            return (Criteria) this;
        }

        public Criteria andCustomerServiceServicePhoneLessThan(String value) {
            addCriterion("customer_service_service_phone <", value, "customerServiceServicePhone");
            return (Criteria) this;
        }

        public Criteria andCustomerServiceServicePhoneLessThanOrEqualTo(String value) {
            addCriterion("customer_service_service_phone <=", value, "customerServiceServicePhone");
            return (Criteria) this;
        }

        public Criteria andCustomerServiceServicePhoneLike(String value) {
            addCriterion("customer_service_service_phone like", value, "customerServiceServicePhone");
            return (Criteria) this;
        }

        public Criteria andCustomerServiceServicePhoneNotLike(String value) {
            addCriterion("customer_service_service_phone not like", value, "customerServiceServicePhone");
            return (Criteria) this;
        }

        public Criteria andCustomerServiceServicePhoneIn(List<String> values) {
            addCriterion("customer_service_service_phone in", values, "customerServiceServicePhone");
            return (Criteria) this;
        }

        public Criteria andCustomerServiceServicePhoneNotIn(List<String> values) {
            addCriterion("customer_service_service_phone not in", values, "customerServiceServicePhone");
            return (Criteria) this;
        }

        public Criteria andCustomerServiceServicePhoneBetween(String value1, String value2) {
            addCriterion("customer_service_service_phone between", value1, value2, "customerServiceServicePhone");
            return (Criteria) this;
        }

        public Criteria andCustomerServiceServicePhoneNotBetween(String value1, String value2) {
            addCriterion("customer_service_service_phone not between", value1, value2, "customerServiceServicePhone");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table project_sponsor_info
     *
     * @mbg.generated do_not_delete_during_merge Wed Apr 13 21:45:49 CST 2022
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table project_sponsor_info
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}