package com.admin.entity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
public class Auth {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth.id
     *
     * @mbg.generated Sun Feb 13 21:55:41 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth.name
     *
     * @mbg.generated Sun Feb 13 21:55:41 CST 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth.title
     *
     * @mbg.generated Sun Feb 13 21:55:41 CST 2022
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth.category_id
     *
     * @mbg.generated Sun Feb 13 21:55:41 CST 2022
     */
    private Integer categoryId;
}