server:
  port: 8001
spring:
  application:
    name: service-provider
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name:  com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/crowdfunding?serverTimezone=UTC&nullCatalogMeansCurrent=true
    username: root
    password: poopybutthole
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: poopybutthole
    jedis:
      pool:
        # 连接池最大连接数，负数表示没有限制
        max-active: 20
        # 连接池最大阻塞等待时间，负数表示没有限制
        max-wait: -1
        # 连接池最大空闲链接
        max-idle: 10
        # 连接池最小空闲链接
        min-idle: 0
    # 链接超时时间
    timeout: 1000

eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true。
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: provider8001
    prefer-ip-address: true

mybatis:
  mapperLocations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.member.entities.po    # 所有Entity别名类所在包