server:
  port: 9001

spring:
  application:
    name: auth
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 1000
  #spingsession
  session:
    store-type: redis


eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true。
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: auth-consumer9001
    prefer-ip-address: true


ribbon:
  eureka:
    enabled: true

# 自定义短信服务
short:
  message:
    host: https://dfsns.market.alicloudapi.com
    path: /data/send_sms
    method: POST
    appcode: 15236a288675494f88cdfb849557aed8
    template-id: TPL_0000