server:
  port: 9002

spring:
  application:
    name: project
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: poopybutthole
    timeout: 1000
  #spingsession
  session:
    store-type: redis

eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true。
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: project-consumer9002
    prefer-ip-address: true

ribbon:
  eureka:
    enabled: true

# 自定义阿里云oss对象存储
aliyun:
  oss:
    access-key-id: LTAI5tRod2DSBcCa65KgKpDu
    access-key-secret: uwM860Qgz32BhZuCeq958BktwhC6vd
    end-point: https://oss-cn-shenzhen.aliyuncs.com
    bucket-domain: https://crowdfunding123.oss-cn-shenzhen.aliyuncs.com
    bucket-name: crowdfunding123

