package com.member.mapper;

import com.member.entities.po.ProjectItemPicturePO;
import com.member.entities.po.ProjectItemPicturePOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProjectItemPictureMapper {

    /* 项目详细图片*/
    int insertRelationshipWithPicture(@Param("itemPicturePath") List<String> itemPicturePath, @Param("projectId") Integer projectId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_item_picture
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    long countByExample(ProjectItemPicturePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_item_picture
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    int deleteByExample(ProjectItemPicturePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_item_picture
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_item_picture
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    int insert(ProjectItemPicturePO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_item_picture
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    int insertSelective(ProjectItemPicturePO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_item_picture
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    List<ProjectItemPicturePO> selectByExample(ProjectItemPicturePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_item_picture
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    ProjectItemPicturePO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_item_picture
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    int updateByExampleSelective(@Param("record") ProjectItemPicturePO record, @Param("example") ProjectItemPicturePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_item_picture
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    int updateByExample(@Param("record") ProjectItemPicturePO record, @Param("example") ProjectItemPicturePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_item_picture
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    int updateByPrimaryKeySelective(ProjectItemPicturePO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_item_picture
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    int updateByPrimaryKey(ProjectItemPicturePO record);
}