package com.member.mapper;

import com.member.entities.po.SponsorConfirmInfoPO;
import com.member.entities.po.SponsorConfirmInfoPOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SponsorConfirmInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sponsor_confirm_info
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    long countByExample(SponsorConfirmInfoPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sponsor_confirm_info
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    int deleteByExample(SponsorConfirmInfoPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sponsor_confirm_info
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sponsor_confirm_info
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    int insert(SponsorConfirmInfoPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sponsor_confirm_info
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    int insertSelective(SponsorConfirmInfoPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sponsor_confirm_info
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    List<SponsorConfirmInfoPO> selectByExample(SponsorConfirmInfoPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sponsor_confirm_info
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    SponsorConfirmInfoPO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sponsor_confirm_info
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    int updateByExampleSelective(@Param("record") SponsorConfirmInfoPO record, @Param("example") SponsorConfirmInfoPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sponsor_confirm_info
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    int updateByExample(@Param("record") SponsorConfirmInfoPO record, @Param("example") SponsorConfirmInfoPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sponsor_confirm_info
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    int updateByPrimaryKeySelective(SponsorConfirmInfoPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sponsor_confirm_info
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    int updateByPrimaryKey(SponsorConfirmInfoPO record);
}