package com.member.mapper;

import com.member.entities.po.SponsorInfoPO;
import com.member.entities.po.SponsorInfoPOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SponsorInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_sponsor_info
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    long countByExample(SponsorInfoPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_sponsor_info
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    int deleteByExample(SponsorInfoPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_sponsor_info
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_sponsor_info
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    int insert(SponsorInfoPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_sponsor_info
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    int insertSelective(SponsorInfoPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_sponsor_info
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    List<SponsorInfoPO> selectByExample(SponsorInfoPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_sponsor_info
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    SponsorInfoPO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_sponsor_info
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    int updateByExampleSelective(@Param("record") SponsorInfoPO record, @Param("example") SponsorInfoPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_sponsor_info
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    int updateByExample(@Param("record") SponsorInfoPO record, @Param("example") SponsorInfoPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_sponsor_info
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    int updateByPrimaryKeySelective(SponsorInfoPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_sponsor_info
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    int updateByPrimaryKey(SponsorInfoPO record);
}