package com.member.mapper;

import com.member.entities.po.TagPO;
import com.member.entities.po.TagPOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    long countByExample(TagPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    int deleteByExample(TagPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    int insert(TagPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    int insertSelective(TagPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    List<TagPO> selectByExample(TagPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    TagPO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    int updateByExampleSelective(@Param("record") TagPO record, @Param("example") TagPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    int updateByExample(@Param("record") TagPO record, @Param("example") TagPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    int updateByPrimaryKeySelective(TagPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag
     *
     * @mbg.generated Wed Apr 13 21:45:49 CST 2022
     */
    int updateByPrimaryKey(TagPO record);
}