server:
  port: 80

spring:
  application:
    name: gateway-zuul80
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: poopybutthole
    timeout: 1000
  #spingsession
  session:
    store-type: redis

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: zuul
    prefer-ip-address: true

zuul:
  ignored-services: "*"  # 表示忽视直接通过application-name访问微服务，必须通过route
  sensitive-headers: "*"  # 在Zuul向其他微服务重定向时，保持原本的头信息（请求头、响应头）
  host:
    connect-timeout-millis: 5000
    socket-timeout-millis: 5000
  routes:
    crowd-protal:
      service-id: auth
      path: /auth/**
    crowd-prodvider:
      service-id: service-provider
      path: /provider/**
    crowd-project:
      service-id: project
      path: /project/**
  prefix: /member

ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000
