package com.admin.entity;

import java.io.Serializable;
import java.util.Date;


public class Admin implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.id
     *
     * @mbg.generated Tue Dec 14 22:51:13 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.login_acct
     *
     * @mbg.generated Tue Dec 14 22:51:13 CST 2021
     */
    private String loginAcct;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.user_pswd
     *
     * @mbg.generated Tue Dec 14 22:51:13 CST 2021
     */
    private String userPswd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.user_name
     *
     * @mbg.generated Tue Dec 14 22:51:13 CST 2021
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.email
     *
     * @mbg.generated Tue Dec 14 22:51:13 CST 2021
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.create_time
     *
     * @mbg.generated Tue Dec 14 22:51:13 CST 2021
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.id
     *
     * @return the value of admin.id
     *
     * @mbg.generated Tue Dec 14 22:51:13 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.id
     *
     * @param id the value for admin.id
     *
     * @mbg.generated Tue Dec 14 22:51:13 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.login_acct
     *
     * @return the value of admin.login_acct
     *
     * @mbg.generated Tue Dec 14 22:51:13 CST 2021
     */
    public String getLoginAcct() {
        return loginAcct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.login_acct
     *
     * @param loginAcct the value for admin.login_acct
     *
     * @mbg.generated Tue Dec 14 22:51:13 CST 2021
     */
    public void setLoginAcct(String loginAcct) {
        this.loginAcct = loginAcct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.user_pswd
     *
     * @return the value of admin.user_pswd
     *
     * @mbg.generated Tue Dec 14 22:51:13 CST 2021
     */
    public String getUserPswd() {
        return userPswd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.user_pswd
     *
     * @param userPswd the value for admin.user_pswd
     *
     * @mbg.generated Tue Dec 14 22:51:13 CST 2021
     */
    public void setUserPswd(String userPswd) {
        this.userPswd = userPswd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.user_name
     *
     * @return the value of admin.user_name
     *
     * @mbg.generated Tue Dec 14 22:51:13 CST 2021
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.user_name
     *
     * @param userName the value for admin.user_name
     *
     * @mbg.generated Tue Dec 14 22:51:13 CST 2021
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.email
     *
     * @return the value of admin.email
     *
     * @mbg.generated Tue Dec 14 22:51:13 CST 2021
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.email
     *
     * @param email the value for admin.email
     *
     * @mbg.generated Tue Dec 14 22:51:13 CST 2021
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.create_time
     *
     * @return the value of admin.create_time
     *
     * @mbg.generated Tue Dec 14 22:51:13 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.create_time
     *
     * @param createTime the value for admin.create_time
     *
     * @mbg.generated Tue Dec 14 22:51:13 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    @Override
    public String toString() {
        return "Admin{" +
                "id=" + id +
                ", loginAcct='" + loginAcct + '\'' +
                ", userPswd='" + userPswd + '\'' +
                ", userName='" + userName + '\'' +
                ", email='" + email + '\'' +
                ", createTime=" + createTime +
                '}';
    }
}